[package]
name = "shell"
version = "0.1.0"
authors = ["myname"]

[lib]
crate-type = ["staticlib"]

[dependencies]
aids = { path = "../aids" }
swi = { path = "../swi" }
vt = { path = "../vt" }
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
rlibc = "1.0.0"
